#!/bin/bash
set -e

usage() {
    echo "Usage: $0 {trusty|xenial} <NAME>" >&2
    exit 1
}

args="$(getopt -o '' -l '' -n "$0" -- "$@")"
eval "set -- $args"

while true; do
    case "$1" in
        --) shift; break;;
        *) usage;;
    esac
done

if [ -z "$1" ] || [ -z "$2" ]; then
    usage
fi

RELEASE="$1"
NAME="$2"

case "$RELEASE" in
    trusty|xenial) ;;
    *) usage;;
esac

if [ "$(id -u)" != 0 ]; then
    echo "Need to be root." >&2
    exit 1
fi

set -x

BASE_PATH=/srv/zulip-chroots
mkdir -p "$BASE_PATH"

CHROOT_DIR="$BASE_PATH"/"$NAME"

apt install ubuntu-archive-keyring
debootstrap "$RELEASE" "$CHROOT_DIR" http://archive.ubuntu.com/ubuntu

# See https://wiki.archlinux.org/index.php/Systemd-nspawn .
run () {
    systemd-nspawn -D "$CHROOT_DIR" -- "$@"
}

run passwd root -d

cat >"$CHROOT_DIR"/etc/apt/sources.list <<EOF
deb http://archive.ubuntu.com/ubuntu $RELEASE main universe
deb http://archive.ubuntu.com/ubuntu $RELEASE-updates main universe
EOF
run apt update
run apt install systemd-services systemd-shim wget

exit 0




## WIP MAYBE OBSOLETE



# 3. basic config


# 4. profit?!

cat <<EOF
Success!
To work in the chroot, run:

  schroot -c $(printf %q "$CHROOT_NAME")
EOF
