#!/bin/bash
set -ex

echo "This is not a real script yet.  Read and run bits by hand." >&2
exit 1

RELEASE="$1"

# 0. Run as root.

# 1. set up schroot
CHROOT_DIR=...
CHROOT_NAME=...

# 2. debootstrap the image
apt install ubuntu-archive-keyring
debootstrap "$RELEASE" "$CHROOT_DIR" http://archive.ubuntu.com/ubuntu

# 3. basic config

# See https://lists.debian.org/debian-user/2012/07/msg01381.html .
# Though https://superuser.com/questions/688733/start-a-systemd-service-inside-chroot
# may ultimately be more relevant -- especially as I have systemd on
# the outside.
cat >"$CHROOT_DIR"/usr/sbin/policy-rc.d <<EOF
#!/bin/sh
exit 101
EOF
chmod +x "$CHROOT_DIR"/usr/sbin/policy-rc.d

cat >"$CHROOT_DIR"/etc/apt/sources.list <<EOF
deb http://archive.ubuntu.com/ubuntu $RELEASE main universe
deb http://archive.ubuntu.com/ubuntu $RELEASE-updates main universe
EOF
schroot -c "$CHROOT_NAME" -- apt update
schroot -c "$CHROOT_NAME" -- apt install systemd-services systemd-shim wget

# 4. profit?!

cat <<EOF
Success!
To work in the chroot, run:

  schroot -c $(printf %q "$CHROOT_NAME")
EOF
